apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      containers:
      - name: mongo-api
        image: {{ .Values.image}}
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: api-configmap
          subPath: appsettings.json
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: 5004
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          tcpSocket:
            port: 5004
      volumes: 
      - name: api-configmap
        configMap:
          name: api-mongo-configmap

      