apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongodb
  template:
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - name: mongodb
        image: localhost:5000/mongo
        ports:
          - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: storage-pv
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: 27017
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          tcpSocket:
            port: 27017
      volumes:
        - name: storage-pv
          persistentVolumeClaim:
            claimName: storage-pvc