apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: jenkins-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: master
  - port: 50000
    targetPort: 50000
    name: slaves