apiVersion: v1
kind: ConfigMap
metadata:
  name: api-mongo-configmap
data:
  appsettings.json: |
    {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
      "AllowedHosts": "*",
      "connstring": "mongodb://mongodb-service:27017",
      "db": "adminHelperDB",
      "collection": "apps"
    }
